### ISSUE TITLE
requirements: need template for protocol description page on didcomm.org

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#10]
#8 mentions that a template for a protocol description page will be provided. This ticket tracks that work.

**Comment by dhh1128** [comment]
See draft here: https://hackmd.io/@dhh1128/H1dzLkMp_/edit

**Comment by dhh1128** [comment]
I want to assign @telegramsam to review this, but I can't until he accepts my invitation to collaborate on the repo.

**Comment by ashcherbakov** [comment]
@dhh1128 
1) Should we define a list of possible common values for the `status` metadata field? Like, alpha, beta, production, etc.
2) How is it expected to do fixes in the protocol? Do we allow overriding of existing protocols in some cases (to fix a typo for example), or every change in the protocol should produce a new version?

**Comment by dhh1128** [comment]
Re. #1: Yes. These values constitute searchable metadata ("give me all protocols that are tagged #production"). Let's use "proposed", "implemented", and "production" for now. (This terminology comes from Hyperledger Aries.)

Re #2: We expect people to follow [semver rules for protocols](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/README.md#semver-rules-for-protocols). We are only going to track minor version, not patch version. So it should be possible for people to submit three types of PRs to the didcomm.org registry:

1. patches
2. minor updates (add an optional field, etc)
3. major updates (require a new field, remove an old field, etc)

It would be awesome if we had automation that could tell what type of PR a developer submits when s/he asks for a protocol to be (re)registered -- but I don't think that's going to be practical. Therefore, I think the instructions for submitting a PR (or the UI that prompts a user to submit a protocol, if we're using a CMS) needs to ask the user some questions to determine which type of change their proposing. Code should then compare the type to the version number and either accept or reject the proposed change depending on whether developers are following the semver rules we've chosen.

**Comment by dhh1128** [comment]
@ashcherbakov : note that I changed some details in the above response, after my first writing -- so if you got an email notification, it will have some stale content. Please read on github to see my latest answer. ^^

**Comment by dhh1128** [comment]
Tagging @TelegramSam. I would like your review of the proposal described above, given the details in the comment stream. Are we ready to close the issue?

**Comment by ashcherbakov** [comment]
@TelegramSam @dhh1128 
Are we ready to close the task?

**Comment by dhh1128** [comment]
Yes. Closing.
