### ISSUE TITLE
design: frameworks and technologies

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#14]
## What
As a team, we should explore possible implementation options and frameworks for https://hackmd.io/s8LmceVRRf-23iTKCy7X8A, so that we can do implementation efficiently and with modern technologies.

## Why
We should define the technologies before start working on the implementation.

## Success Criteria
- Create a small doc (Wiki page in this repo) with the names of technologies/frameworks to be used, and a short description how every technology can help
- Decide if we need a CMS
- Decide how Search will be done
- Decide how to implement pagination for search results
- Please take into account the following when defining technologies:
    - match specification from ttps://hackmd.io/s8LmceVRRf-23iTKCy7X8A, so there must be no backend, and the site should be based on GitHub pages.
    - the site should look nice and fancy without adding too much complexity
- Consider at least the following technologies: Jekyll, Netlify CMS

**Comment by Merciful12** [comment]
after a quick research I have next results

**Jekyll**
_pros_: 
  - it's out-of-the-box solution

_cons_: 
  - it is not flexible at all, there is no way to use plugins other than are provided by github. 
  - In order to use a pagination, the pages (protocol definitions in our case) must be named like `YEAR-MONTH-DAY-title.MARKUP`. It breaks the url specs

It's suggested to use **Gatsby** as main framework. The only _cons_ here: it requires a little bit more setup to provide auto deploys.

**Comment by Merciful12** [comment]
Netlify CMS + GitHub Pages have a problem without a server since github doesn’t support implicit auth

more details:
https://github.com/netlify/netlify-cms/issues/4731

**Comment by Merciful12** [comment]
researched search libraries: `fuse.js`, `js-search` and `flexsearch`

`fuse.js` https://fusejs.io/
pros: good documentation, well maintained, provides fuzzy search
cons: can be extremely slow on large data sets

`js-search` https://github.com/nextapps-de/flexsearch
just works well 

`flexsearch` https://github.com/nextapps-de/flexsearch
pros: the fastest one, flexible
cons: has no types definitions, not a stable version yet (0.7.2)

It's suggested to use js-search (as the golden mean), but anyway the search can be switched easily if needed

**Comment by Merciful12** [comment]
Pagination can be implemented on client side. 
Also `Browse All` paginated pages can be generated on build time, but without any filters, sort etc.
`Protocol Definition Details` page should be enough for indexing by search engine (i.e. Google), so there is no need to generate static version of `Browse All`

**Comment by ashcherbakov** [comment]
FYI @dhh1128 
Summary:
- all technologies are defined: Gatsby (not Jeskyll), js-search
- it looks like we can not use any CMS and have to go with initially proposed PR-based protocol submitting because of the following:
  - DCO need in didcomm.org repo (that can probably be solved)
  - A need for a backend to handle github-based auth (https://github.com/sicpa-dlab/didcomm-gemini/issues/14#issuecomment-882612996)
