### ISSUE TITLE
requirements: write general spec for peer DID libs

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#16]
We need a general description of features expected from peer DID libs

**Comment by dhh1128** [comment]
Here is a first attempt at such a spec: https://hackmd.io/@dhh1128/HJ2HpeoTO/edit

**Comment by ashcherbakov** [comment]
@dhh1128 
1) Do we have any requirements about where to store the peer did docs? It looks like the python implementation stores them in a file.
I think we will need to have a pluggable `storage abstraction` with, for example, one default implementation as `file storage`. 
2) Do you think we may need to implement other (pluggable) implementations for the storage in addition to file storage? For example, KV storage (such as leveldb, rocksdb) or sqlite.

**Comment by dhh1128** [comment]
Re. #1: The DID docs are not especially secret. My suggestion is to store them in the file system under ~/.did:peer. That would be a place accessible to all programming languages, and it would be tied to the current user's permissions and storage in a useful way.

Re #2: No. This would be a nice-to-have extension but we should not spend any energy on it between now and October.

**Comment by ashcherbakov** [comment]
OK. Makes sense to use user home directory as a default root. I think we should support configurable root folder, as it can be useful on some platforms (such as mobile devices).
