### ISSUE TITLE
design: DIDComm Java/Kotlin API

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#17]
## What
Define API and interfaces for Java/Kotlin DIDComm library matching https://hackmd.io/gIk7LWd_QZuzApNfZ4KEIA

## Why
We need to define and review the API and interfaces and make sure that it's clear, simple, convenient and idiomatic before work on the implementation.

## Success Criteria
- Decide if we do the library in Java or in Kotlin
- Create a project for Java/Kotlin DIDComm
- Define required interfaces and API calls. It should not have any implementation, only stubs.
- Add API docs to the calls
- If there are any other diagrams/docs created while working on the task, make it available as a Wiki page in this repo.
- Review the API with the team
- Take into account the following when designing and reviewing the API:
   - API is clear, simple and convenient
   - API matches the latest version of the DID Comm spec https://identity.foundation/didcomm-messaging/spec/
   - API matches https://hackmd.io/gIk7LWd_QZuzApNfZ4KEIA
   - API is idiomatic for the language

**Comment by dhh1128** [comment]
I suggest that DSR should be assigned this ticket, with @CluEleSsUK performing a review and maybe providing some input.

**Comment by AnomalRoil** [comment]
You can assign multiple stakeholders to a given issue (up to 10 actually)...

**Comment by ashcherbakov** [comment]
As we have separate In Progress and In Review columns, I would prefer to assign it to developer(s) who actually work on design/implementation when In Progress state, and then re-assign a task for review/customer validation once it's ready (In Review state), so that it's more obvious and clear who works on the task, and from whom we expect a feedback.

**Comment by ashcherbakov** [comment]
PR: https://github.com/sicpa-dlab/didcomm-jvm/pull/3
