### ISSUE TITLE
design: DIDComm JavaScript/TypeScript API

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#19]
## What
Define API and interfaces for JavaScript/TypeScript DIDComm library matching https://hackmd.io/gIk7LWd_QZuzApNfZ4KEIA

## Why
We need to define and review the API and interfaces and make sure that it's clear, simple, convenient and idiomatic before work on the implementation.

## Success Criteria
- Create a project for JavaScript/TypeScript DIDComm
- Define required interfaces and API calls. It should not have any implementation, only stubs.
- Add API docs to the calls
- If there are any other diagrams/docs created while working on the task, make it available as a Wiki page in this repo.
- Review the API with the team
- Take into account the following when designing and reviewing the API:
   - API is clear, simple and convenient
   - API matches the latest version of the DID Comm spec https://identity.foundation/didcomm-messaging/spec/
   - API matches https://hackmd.io/gIk7LWd_QZuzApNfZ4KEIA
   - API is idiomatic for the language

**Comment by vimmerru** [comment]
Here is the link to draft version https://hackmd.io/DJ4p9DNjQd6snsulOXLG0Q?view

**Comment by ashcherbakov** [comment]
Will be done in the scope of #30
