### ISSUE TITLE
research: audit JOSE libraries in JavaScript/TS for ECDH-1PU compatibility

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#2]
We want people to be able to implement [ECDH-1PU Draft 4](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04) using a standard JOSE library in JavaScript/TypeScript. When we implemented Draft 3 of that RFC in Rust, we were able to do it with just [a few lines of code](https://github.com/andrewwhitehead/aries-askar/commit/17a4e0fbcb961b0e5d1f375b287681af982eb0ef#diff-c1f73351aa42c3dca3eafea450fcbdaa63000001c8f489aa11fae2b3d7f754d3R53); the purpose of this ticket is to decide whether it is true in JavaScript. If it is not true, we need to discuss the best way to patch the libraries -- contribute a patch to mainstream JOSE libraries, fork the mainstream JOSE libraries and add our feature, or write a very simple version of JOSE that's adequate for DIDComm with ECDH-1PU only.

**Success Criteria**
- Write a doc (this repo Wiki) with the research summary
- The doc should contain multiple Options with cons and pros how we can implement ECDH-1PU for the target language
- There should be one proposed option that we can discuss and approve with the team
- Take into account the following when describing the existing libraries:
  - Whether all required curves required for DID Comm are supported (X25519 is must have for the first release; P-256 and P-384 will also be needed)  
  - What encryption protocols required for DID Comm are supported in the library (XC20P, A256GCM, A256CBC-HS512)
  - What signature protocols required for the DID Comm are supported in the library (EdDSA (with crv=Ed25519), ES256, ES256K)
  - What Key Wrapping algorithms required for the DID Comm are supported (ECDH-ES+A256KW)
  - License, compatibility with Apache 2, possible need for modifications of the library 
  - Whether the library is open or closed to external contributions
  - How ECDH-1PU can be supported: 
       - contribution to the upstream
       - support in a fork (no upstream contribution for now)
       - implement in DID Comm lib code on top of JOSE lib
  - What base crypto lib will be used 
  - Are there any know security issues in the lib? How popular is the lib?
  - Supported platforms
       - backend (node.js)
       - browsers support
       - support on Mobile platforms in case of ReactNative

**Comment by vimmerru** [comment]
@dhh1128 Hi Daniel, the PR is you mention may have relation to migration of custom crypto code from ECDH-1PU v3 to ECDH-1PU v4. I never saw any PR related to support of  ECDH-1PU to common JOSE libraries. Also i read readmes of some such libraries and they are quire sceptic about support of any new/unstable/not widely adopted crypto. 

Maybe we need to define more detailed research plan. Questions we can answer:

1. Provide list of the most common JOSE libraries
2. Answer is it possible to add ECDU-1PU support without significant architecture changes or addining any new crypto dependencies.
3. Estimate probability of the PR be merged to mainstream. May require communication with maintainers and evaluation of PR rules.

**Comment by dhh1128** [comment]
That's a good plan. I like it.

I want to allow the following set of answers to be acceptable:

1. The most common JOSE library for {programming language X} doesn't have support for ECDH-1PU. (I think this will be the most common answer -- maybe even universal)
2. Adding support for ECDH-1PU into that library is unlikely to work, either because the library is difficult to work with, or because its maintainers are suspicious of changes. (I also expect this to be common.)
3. Writing a few lines of code *outside* the JOSE library (maybe, less than 200) is an easy way to use the JOSE library in question, but to get ECDH-1PU support. No dirty hacks or architectural changes are required. This is what we did for Draft 3, and I'm hoping it is also common for Draft 4.

If we observe such a combination of answers, then I think the way forward is easy: we just write those extra lines of code, and we put them in our didcomm libraries. The generic JOSE libraries for {programming language X} don't get ECDH-1PU support, but anybody using our didcomm libraries can use ECDH-1PU easily, and can also use their languages generic JOSE libraries without a conflict.

**Comment by ajslack** [comment]
A note primarily for @dhh1128 and @CluEleSsUK to input into the discussion on support for browser based javascript. 

While not imperative browser based support would let us use this in Framer for demos, which is a nice-to-have.

**Comment by AnomalRoil** [comment]
Any chance we could have a link to the HackMD page with the comparison chart and tables that we were shown today?

**Comment by ashcherbakov** [comment]
- JS research: [link](https://hackmd.io/@IyhpRay4QVC_ozugDsQAQg/S1QlYJN0d)
- Our proposal: [link](https://hackmd.io/7c1bcf0LTQ2xvXkDzcesZQ)
