### ISSUE TITLE
design: peerdid Python API

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#21]
## What
Define API and interfaces for Python peerdid library matching the spec https://hackmd.io/OTmCk7d1SS6MYWNoXsWXVg
## Why
We need to define and review the API and interfaces and make sure that it's clear, simple, convenient and idiomatic before work on the implementation.

## Success Criteria
- Create a project for Python peerdid or fork https://github.com/evernym/pypeerdid
- Review the API from https://github.com/evernym/pypeerdid, adjust if needed
- Add API docs to the calls if missing
- If there are any other diagrams/docs created while working on the task, make it available as a Wiki page in this repo.
- Review the API with the team
- Take into account the following when designing and reviewing the API:
   - API is clear, simple and convenient
   - API matches the latest version of the peerdid spec https://identity.foundation/peer-did-method-spec/
   - API matches the spec https://hackmd.io/OTmCk7d1SS6MYWNoXsWXVg
   - API is idiomatic for the language

**Comment by DenisRybas** [comment]
A PR with the peerdid API proposal in Python: https://github.com/sicpa-dlab/peer-did-python/pull/1
