### ISSUE TITLE
impl: DIDComm Java/Kotlin MVP

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#29]
## What
Implement DIDComm Java/Kotlin as defined in #17 

## Success Criteria
- All API calls are implemented and functional
- All API calls are covered by unit/integration tests
- Auxiliary functions are covered by unit tests (try following TDD)
- A simple README with examples is created
- Need to work on Linux, Windows, Macos, Android
- It's sufficient to support Ed25519 curve only
- Need to have ECDH-1PU support as designed in #3 and implemented in #68
- Forward and fromPrior support will be added in next tickets

**Comment by ashcherbakov** [comment]
PR: https://github.com/sicpa-dlab/nimbus-jose-jwt/pull/4

**Comment by ashcherbakov** [comment]
Plan of attack:
1) example in-memory resolvers sufficient for tests (not more)
2) tests for pack/unpack against created test vectors
3) message builder (message+attachments)
4) add JOSE dependency
5) pack_encrypted w/o Forward
6) pack_signed w/o Forward
7) pack_plaintext w/o Forward
8) Make sure all tests pass; add more tests
9) Forward support. Add more tests.
10) from_prior support. Tests.
11) debug, more tests

**Comment by asmarty** [comment]
items that need to be completed or improved
1. converting keys from base58 to jwk 
2. improvement of the exceptions. bring all exceptions in different libraries to the same form
3. add documentation for all public methods 
4. add more negative tests

**Comment by asmarty** [comment]
need support for all verification method types as well 
- JSON_WEB_KEY_2020,
- X25519_KEY_AGREEMENT_KEY_2019,
- ED25519_VERIFICATION_KEY_2018,
- ECDSA_SECP_256K1_VERIFICATION_KEY_2019,
- OTHER (throw exception?)

**Comment by ashcherbakov** [comment]
7. External keys support (when a verification method in a DID DOC is reference to another DID DOC).

**Comment by asmarty** [comment]
add encryption negative tests

Common tests 

1. decrypt empty message ("") expected result 
2. decrypt empty JSON ({})
3. decrypt message where required headers is missed 
    a. recipients
    b. protected
    c. ciphertext
    d. tag
    e. iv
4. unsupported "alg" and "enc" headers
5. unsupported message onion 
    a. auth -> anon
    b. anon -> anon
    c. anon -> auth -> auth
    d. anon -> auth -> anon

Anon tests 

1. decryptForAllKyes=true - one of recipient's key is invalid
2. decryptForAllKyes=true - one of recipient's key not found in secret manager 

Auth test

1. decryptForAllKyes=true - one of recipient's key is invalid
2. decryptForAllKyes=true - one of recipient's key not found in secret manager 
3. alice did doc not found
4. alice sender key not found
5. alice and bob keys from different curves

**Comment by ashcherbakov** [comment]
- MVP is done
- PRs:
  - https://github.com/sicpa-dlab/didcomm-jvm/pull/4
  - https://github.com/sicpa-dlab/didcomm-jvm/pull/5
  - https://github.com/sicpa-dlab/didcomm-jvm/pull/6
  - https://github.com/sicpa-dlab/didcomm-jvm/pull/7
- More tests and fixes will be done in #94 
- Forward and DID rotation are not part of this ticket and will be done in the scope of #85 and #88.
