### ISSUE TITLE
research: audit JOSE libraries in Java/Kotlin for ECDH-1PU compatibility

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#3]
We want people to be able to implement [ECDH-1PU Draft 4](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04) using a standard JOSE library in a JVM language. When we implemented Draft 3 of that RFC in Rust, we were able to do it with just [a few lines of code](https://github.com/andrewwhitehead/aries-askar/commit/17a4e0fbcb961b0e5d1f375b287681af982eb0ef#diff-c1f73351aa42c3dca3eafea450fcbdaa63000001c8f489aa11fae2b3d7f754d3R53); the purpose of this ticket is to decide whether it is true in a JVM language. If it is not true, we need to discuss the best way to patch the libraries -- contribute a patch to mainstream JOSE libraries, fork the mainstream JOSE libraries and add our feature, or write a very simple version of JOSE that's adequate for DIDComm with ECDH-1PU only.

**Success Criteria**
- Write a doc (this repo Wiki) with the research summary
- The doc should contain multiple Options with cons and pros how we can implement ECDH-1PU for the target language
- There should be one proposed option that we can discuss and approve with the team
- Take into account the following when describing the existing libraries:
  - Whether all required curves required for DID Comm are supported (X25519 is must have for the first release; P-256 and P-384 will also be needed)  
  - What encryption protocols required for DID Comm are supported in the library (XC20P, A256GCM, A256CBC-HS512)
  - What signature protocols required for the DID Comm are supported in the library (EdDSA (with crv=Ed25519), ES256, ES256K)
  - What Key Wrapping algorithms required for the DID Comm are supported (ECDH-ES+A256KW)
  - License, compatibility with Apache 2, possible need for modifications of the library 
  - Whether the library is open or closed to external contributions
  - How ECDH-1PU can be supported: 
       - contribution to the upstream
       - support in a fork (no upstream contribution for now)
       - implement in DID Comm lib code on top of JOSE lib
  - What base crypto lib will be used 
  - Supported platforms
       - Android
       - [Optionally] Multiplatform support on iOS?
  - Are there any know security issues in the lib? How popular is the lib?

**Comment by spivachuk** [comment]
Please find the results of Java JOSE libraries research at the link: https://hackmd.io/@FCN75Uk9TCqMmxSE6vEn5A/rkhCBUP0O

**Comment by ashcherbakov** [comment]
- Java research: [link](https://hackmd.io/@FCN75Uk9TCqMmxSE6vEn5A/rkhCBUP0O)
- Our proposal: [link](https://hackmd.io/7c1bcf0LTQ2xvXkDzcesZQ)
