### ISSUE TITLE
Validation of Protocol Definitions

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#37]
## What
As a protocol author, I want the website to validate a protocol definition submitted by me, so that I can be sure that the protocol is correctly formatted before publishing it.

## Success Criteria
- the requirements and a list of validation checks to be performed can be found in https://hackmd.io/s8LmceVRRf-23iTKCy7X8A#Best-practices-and-CICD
- Other things to be validated:
   - Status metadata: should be one of the following: proposed, demonstrated, production.
   - Updating a protocol definition (see below)
- GitHub Actions CI should be configured in a way to do all necessary validation
- if we go with CMS option, then some changes can also be checked on the CMS level
- if we are confident in quality and fullness of our PR tests, we may enable automatic merge of PRs if all the tests passed

## Updating the protocol definition
We expect people to follow semver rules for protocols. We are only going to track minor version, not patch version. So it should be possible for people to submit three types of PRs to the didcomm.org registry:

- patches (typos, clarifications, better docs; version number won't change)
- minor updates (add an optional field, etc; version number's second digit increments)
- major updates (require a new field, remove an old field, etc; version number's first digit increments)

It would be awesome if we had automation that could tell what type of PR a developer submits when s/he asks for a protocol to be (re)registered -- but I don't think that's going to be practical. Therefore, I think the instructions for submitting a PR (or the UI that prompts a user to submit a protocol, if we're using a CMS) needs to ask the user some questions to determine which type of change they're proposing. Code should then compare the type to the version number and either accept or reject the proposed change depending on whether developers are following the semver rules we've chosen.

**Comment by Merciful12** [comment]
Validation should be like this
if it's pull request and it changes protocols folder:
  - check PIURI
    - structure: name (folder), version (folder), readme (markdown file)
    - name + version should be unique (my-protocol-1 and MyProtocol1 are the same)
  - check protocol content (readme markdown file)
    - keywords (hashtags):
      - array
      - required
      - unique (`finance`, `financial` and `finances` are the same)
    - licence
      - string (possible url?)
      - required
    - body
      - no broken hyperlinks
      - no html

**Comment by Merciful12** [comment]
additional validation checks
- name and version from piuri are equal to name and version from file structure
- title from metadata is equal to file structure (after stripping separators)
- body of markdown has no dangerous html
- author of pull request is equal to publisher in metadata
- protocol name and version are unique (protocol1 and protcol-1)
