### ISSUE TITLE
research: audit JOSE libraries in Rust for ECDH-1PU compatibility

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#4]
We want people to be able to implement [ECDH-1PU Draft 4](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04) using a standard JOSE library in Rust. When we implemented Draft 3 of that RFC in Rust, we were able to do it with just [a few lines of code](https://github.com/andrewwhitehead/aries-askar/commit/17a4e0fbcb961b0e5d1f375b287681af982eb0ef#diff-c1f73351aa42c3dca3eafea450fcbdaa63000001c8f489aa11fae2b3d7f754d3R53); the purpose of this ticket is to decide whether it is still true for Draft 4. If it is not true, we need to discuss the best way to patch the libraries -- contribute a patch to mainstream JOSE libraries, fork the mainstream JOSE libraries and add our feature, or write a very simple version of JOSE that's adequate for DIDComm with ECDH-1PU only.

**Comment by ashcherbakov** [comment]
JOSE research for Rust: https://hackmd.io/HUaWkgNhRKa_9GBvlNU4gA

**Comment by ashcherbakov** [comment]
In general, we have two options:
1. [Implement everything in DID Comm](https://hackmd.io/HUaWkgNhRKa_9GBvlNU4gA#1-Implement-in-DID-Comm)
2. [Implement everything in DID Comm on top of askar-crypto](https://hackmd.io/HUaWkgNhRKa_9GBvlNU4gA#2-Askar-crypto--implement-in-DID-Comm)

Both options seem reasonable.
We just need to define where we would like to see a reference implementation of ECDH-ES and ECDH-1PU in Rust: in askar-crypto or in DID Comm Rust lib.

**Comment by ashcherbakov** [comment]
@dhh1128 
Am I correct that our final decision is to go with Option 2, so that we use and contribute to the shared implementation of ECDH-1PU from askar-crypto?

**Comment by dhh1128** [comment]
Yes, Option 2 is my preference. I am proposing that the preference turn into a decision on the basis of the assumption that the difference in effort between these two is not great. If, after we begin working in `askar-crypto`, we learn that it is much harder than we expected, we can revisit the decision.
