### ISSUE TITLE
design: CI/CD

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#40]
## What
As a team, we need to define an approach for CI/CD for the libraries.

## Success Criteria
Prepare a short overview how CI/CD/Releasing will look like
- What technology/framework to use
- How CI will look like
- What platforms should be tested
- How Release process should look like

**Comment by ashcherbakov** [comment]
The CI/CD Design is created in https://github.com/sicpa-dlab/didcomm-gemini/wiki/CI-CD-Design

**Comment by ashcherbakov** [comment]
Some details about multi-platform and mobile platforms support may be added later once we have more clear understanding about how and whether we use it.

**Comment by dhh1128** [comment]
I just wanted to say that I've read the design doc and I am in harmony with it. As far as I'm concerned, it is ready to approve and say "done" on the issue.
