### ISSUE TITLE
impl: DIDComm JOSE part in Rust 

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#70]
## What
We need to implement JOSE-related parts and algorithms required by DID Comm that are not provided by standard JOSE libraries.
See TBD research from #4. 

In particular we need to implement
- ECDH-1PU
- XC20P
- JSON serialization
- Multi-recipient support

It was decided to do implementation TBD

## Success Criteria
TBD

**Comment by vimmerru** [comment]
Implemented and tested in https://github.com/sicpa-dlab/didcomm-rust/pull/3
