### ISSUE TITLE
need standard action to generate static site to gh_pages branch

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#78]
This is NOT a request for didcomm.org, but I am logging it in the didcomm.org project because it will require some github action work that's quite similar to the work we've done on the didcomm.org website. 

I need a github action that I can trigger in various ways (e.g., manually, when a PR is raised, etc), that will run a shell command that produces static html and publishes it.

This is NOT going to use gatsby or jekyll or mkdocs or any other static site generator, because the static website generator I need to run is a custom python script. It generates a glossary from a [Terms Wiki](https://wiki.trustoverip.org/display/HOME/Terms+Wikis), and it doesn't use any templating engine.

The script I want to run is located at https://github.com/trustoverip/tt. I have not yet made the script install via pypi, but I will do so. Once that's done, here is how the action needs to work:

- Start with a github action runner that has python 3.x and git installed
- pip install tt
- Run the shell command `tt glossary GLOSSARY_DEF_FILE >index.html` (where GLOSSARY_DEF_FILE is an input to the action)
- Copy index.html to the gh_pages branch of the repo

This action will be deployed in various repos, so I need a documented, reproducible recipe for how to do this.

**Comment by Merciful12** [comment]
Action Guide

# tt Run and Publish

This worflow provides the following functionality for GitHub Actions users:

- Setup Python (3.x by default) environment using [setup-python](https://github.com/actions/setup-python)
- Install deps
- Run the shell command
- Push produced files to a branch (gh-pages by default)

# Usage

Provide **access-token**: [GitHub Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) with
  the `repo` scope. This is **required** to push the site to the repo after
  script finish. You should store this as a [secret](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets) called `ACCESS_TOKEN`
  in your repository.

The worflow has two inputs:
- glossaryDefFile
- deployBranch

**Manual Run**

[Manually running the workflow](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

**Automation Run**

Change the trigger event in the next lines if it is needed
```yaml
on:
  push:
    branches: [main]
```
**Variables**

Change default input values `DEFAULT_GLOSSARY_DEF_FILE` and/or `DEFAULT_BRANCH` in the next lines if it is needed
```yaml
- name: Set variables
  env:
    DEFAULT_GLOSSARY_DEF_FILE: glossary.json
    DEFAULT_DEPLOY_BRANCH: gh_pages
```

Change the shell command if it is needed
```yaml
- name: Run script
   run: ./tt/bin/tt glossary ${{ env.GLOSSARY_DEF_FILE }} >index.html
```

Change packages to install if it is needed
```yaml
- name: Install deps
  run: |
    git clone https://github.com/trustoverip/tt.git
    python -m pip install marko
```
